# Makefile: to list out common commands for this pebble app
PHONE_IP=192.168.1.39 # this varies

build:
	pebble build

run:
	pebble install --phone $(PHONE_IP)

debug:
	pebble install --emulator chalk
